version: '3.8'
services:
  securitylib:
    image: "securitylib:latest"
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "upgrade"
    volumes:
      - ./:/securitylib
    environment:
      PYTHONPATH: "/securitylib"
